spring:
  datasource:
    url: jdbc:${POSTGRES_HOST:postgresql://localhost}:5432/evolution
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
  
  
#Authorization server identifier (s). That is, the "aud" parameter.
authorizationserver:
  auth.token.url: http://host.docker.internal:8080/auth/platform/token/tao 
  
tao:
  private.key: classpath:tao_private_key.key
  public.key: classpath:tao_public_key.key  	
  tool.kid: toolKey
  tool.jwks.url: https://lti-public-devkit.dev.gcp-eu.taocloud.org/lti1p3/.well-known/jwks/toolSet.json