jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
  
  
#Authorization server identifier (s). That is, the "aud" parameter.
authorizationserver:
  auth.token.url: http://host.docker.internal:8080/auth/platform/token/tao 
  
tao:
  tool.jwks.url: https://lti-public-devkit.dev.gcp-eu.taocloud.org/lti1p3/.well-known/jwks/toolSet.json